---
engines:
  duplication:
    enabled: false
  fixme:
    enabled: true
  phpmd:
    enabled: true
    checks:
      Naming/ShortVariable:
        enabled: false
      Naming/LongVariable:
        enabled: false
      Naming/ShortMethodName:
        enabled: false
      Naming/LongMethodName:
        enabled: false
    config:
      file_extensions: "php"
      rulesets: "unusedcode,codesize,naming,design,controversial,phpmd.xml"
  phpcodesniffer:
    enabled: true
    config:
      file_extensions: "php"
      standard: "PSR1,PSR2"
ratings:
  paths:
  - "**.php"
exclude_paths:
  - vendor
